name: LaTeX Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        scheme: full
        
    - name: Install additional tools
      run: |
        tlmgr update --self
        tlmgr install chktex lacheck
        
    - name: Run ChkTeX
      run: |
        echo "=== Linting LaTeX files with ChkTeX ==="
        chktex -n1 -n8 -n24 -n26 -n36 -q Vatsal_CV.tex || true
        chktex -n1 -n8 -n24 -n26 -n36 -q Vatsal_CV-shortCV.tex || true
        chktex -n1 -n8 -n24 -n26 -n36 -q moderncvcolordarkmagenta.sty || true
      continue-on-error: true
        
    - name: Run lacheck
      run: |
        echo "=== Running lacheck ==="
        lacheck Vatsal_CV.tex || true
        lacheck Vatsal_CV-shortCV.tex || true
      continue-on-error: true
        
    - name: Validate Bibliography
      run: |
        echo "=== Validating bibliography ==="
        biber --tool --validate-datamodel mypublications.bib || true
      continue-on-error: true
        
    - name: Check compilation
      run: |
        echo "=== Testing compilation ==="
        make all
        
    - name: Check for undefined references
      run: |
        echo "=== Checking for undefined references ==="
        make check-refs